### ISSUE TITLE
Settings form layout

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/timeliner#251] opened 2019-01-29 11:51 UTC
We encountered some accessibility issues with the layout.

We should move columns closer together OR change to single column.

Also tidy up spacing.

**Comment by cjcolvar** [comment] 2019-03-21 16:39
Duplicate of https://github.com/digirati-co-uk/timeliner/issues/274?

**Closed** 2019-03-21 16:52 UTC
Labels: :triangular_ruler:  UX
